name: Comment on failed linting

on:
  workflow_run:
    workflows: ["linter-bot-comment"]
    types:
      - completed
    
jobs:
  comment:
    # Add the following filter to only run on pull request events
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
        - name: Comment on pull request
          uses: actions/github-script@v6
          with:
              github-token: ${{secrets.GITHUB_TOKEN}}
              script: |
                const failedJobs = '${{ github.event.workflow_run.jobs.lint.outputs }}';
                let message = `Linter is failing on your pull request. Please enable pre-commit hooks (info under this link: ...) \n\n`;
                if (failedJobs.includes('isort')) {
                    message += `For the issue with isort, you can run:\n\n\`isort .\`\n\nAnd then commit the changes:\n\n\`git commit -am "ran isort"\`\n\`git push\`\n`;
                }
                if (failedJobs.includes('black')) {
                    message += `For the issue with black, you can run:\n\n\`black .\`\n\nAnd then commit the changes:\n\n\`git commit -am "ran black"\`\n\`git push\`\n`;
                }
                github.rest.issues.createComment({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body: message,
                })
    