name: linter

on:
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          source build_tools/shared.sh
          # Include pytest compatibility with mypy
          pip install pytest flake8 $(get_dep mypy min) $(get_dep black min) cython-lint

      - name: Run linting
        run: |
          ./build_tools/linting.sh &> /tmp/linting_output.txt
          cat /tmp/linting_output.txt

      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: lint-log
          path: /tmp/linting_output.txt
          retention-days: 1
