# This linter job on GH actions is used to trigger the commenter bot
# in bot-lint-comment.yml file. It stores the output of the linter to be used
# by the commenter bot.
name: linter

on:
  - pull_request_target

permissions:
  pull-requests: write
  issues: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          source build_tools/shared.sh
          # Include pytest compatibility with mypy
          pip install pytest flake8 $(get_dep mypy min) $(get_dep black min) cython-lint requests

      - name: Run linting
        run: ./build_tools/linting.sh &> /tmp/linting_output.txt

      - name: Print log
        if: always()
        run: cat /tmp/linting_output.txt

      - name: Process Comments
        if: always()
        id: process-comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: python ./build_tools/get_comment.py
