name: pytest

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  has-it:

    runs-on: ${{ matrix.os }}
    if: ${{ (github.repository == 'adrinjalali/gh-action-test') }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ["3.7", "3.10"]

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{github.event.after}}    
    - run: echo PR_COMMIT_MESSAGE=$(git log -1 --pretty=format:\"%s\") >> $GITHUB_ENV
    - run: echo $PR_COMMIT_MESSAGE
    - name: Set up Python ${{ matrix.python }}
      if: contains(env.PR_COMMIT_MESSAGE, '[CI inference]')
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}

  has-it-not:

    runs-on: ${{ matrix.os }}
    if: ${{ (github.repository == 'adrinjalali/gh-action-test') }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ["3.7", "3.10"]

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{github.event.after}}    
    - run: echo PR_COMMIT_MESSAGE=$(git log -1 --pretty=format:\"%s\") >> $GITHUB_ENV
    - run: echo $PR_COMMIT_MESSAGE
    - name: Set up Python ${{ matrix.python }}
      if: contains(env.PR_COMMIT_MESSAGE, '[CI inference]')
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
